#!/usr/bin/env bash

source $HOME/.config/debrewery/debrewery.cfg

repo=`basename $PWD | cut -f 1 -d '.'`
commitmessage=`git log -1 HEAD --pretty=format:%s`
stable_hash=`git rev-list stable | head -n 1`
current_hash=`git rev-parse HEAD`
build_environment="testing"

if [[ $stable_hash != $current_hash ]]; then
    build_environment="testing"
else
    build_environment="production"
fi

for distro in $DEBREW_DISTRIBUTIONS; do
    for arch in $DEBREW_ARCHITECTURES; do
        chroot /opt/chroot/$distro/$arch /usr/lib/debrewery/debrewery-agent.sh -d $distro -a $arch -e $build_environment -r $repo -m $commitmessage &
    done
done

wait

echo -e "\a"
